export const POOL_ABI = [
  {
    inputs: [],
    name: "reservesInfo",
    outputs: [
      { name: "liquidationBondEscrowed_", type: "uint256" },
      { name: "reserveAuctionUnclaimed_", type: "uint256" },
      { name: "reserveAuctionKicked_", type: "uint256" },
      { name: "lastKickedReserves_", type: "uint256" },
      { name: "totalInterestEarned_", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "amount_", type: "uint256" }],
    name: "takeReserves",
    outputs: [{ name: "amount_", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "kickReserveAuction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "collateralAddress",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "quoteTokenAddress",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "quoteTokenScale",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
